#  _____     _               
# |  _  |___| |_ _ _ ___ ___ 
# |     |  _|  _| | |  _| . |
# |__|__|_| |_| |___|_| |___|
# http://32bits.io/Arturo/
#

# +----------------------------------------------------------------------------+
# | BUILD CONFIGURATION
# +----------------------------------------------------------------------------+
ARTURO_VERSION_STRING           := {{env.version}}
PROJECT_NAME                    := {{source.name}}
TARGET_PACKAGE                  := {{preferences.target_package}}
TARGET_PLATFORM                 := {{preferences.target_platform}}
BOARD                           := {{preferences.board}}
INO_PROCESSOR                   := {{commands.preprocess}}

# +----------------------------------------------------------------------------+
# | DIRECTORIES AND CONFIGURATIONS
# +----------------------------------------------------------------------------+
DIR_BUILD                       := {{project.builddir}}
DIR_SOURCE                      := {{source.dir}}
DIR_MAKEFILE                    := $(CURDIR)
# Arduino macro {build.path} resolves to $(DIR_BUILD_PATH).
DIR_BUILD_PATH                  := $(DIR_BUILD)/$(TARGET_PACKAGE)/$(TARGET_PLATFORM)/$(BOARD)

# +----------------------------------------------------------------------------+
# | MAKEFILE INCLUDE AS COMMAND
# +----------------------------------------------------------------------------+
MAKE_PROJECT                    := $(DIR_BUILD)/{{templates.makeproject}}

# +----------------------------------------------------------------------------+
# | TARGETS
# +----------------------------------------------------------------------------+

# we are cross compiling. Any default rule will be incorrect.
.SUFFIXES:

.PHONY : all
all:
	# Build all the things.

.PHONY : init
init: 
	@echo "This is not a valid target. Did you mean '{{commands.init}}'?"

.PHONY : clean
clean:
	rm -rf $(DIR_BUILD)

$(MAKE_PROJECT): {{this.filename}}
	{{commands.makegen}} {{arguments.path}} $@ {{arguments.template}} "makeproject"

# optional local overrides
-include local.mk

DIR_MAKEFILE := $(CURDIR)/$(DIR_BUILD)
-include $(MAKE_PROJECT)
