#  _____     _               
# |  _  |___| |_ _ _ ___ ___ 
# |     |  _|  _| | |  _| . |
# |__|__|_| |_| |___|_| |___|
# http://32bits.io/Arturo/
#

# +----------------------------------------------------------------------------+
# | BUILD CONFIGURATION
# +----------------------------------------------------------------------------+
ARTURO_VERSION_STRING           := {{env.version}}
PROJECT_NAME                    := {{source.name}}
TARGET_PACKAGE                  := {{preferences.target_package}}
TARGET_PLATFORM                 := {{preferences.target_platform}}
BOARD                           := {{preferences.board}}

# +----------------------------------------------------------------------------+
# | DIRECTORIES AND CONFIGURATIONS
# +----------------------------------------------------------------------------+
DIR_BUILD                       := {{project.builddir}}
DIR_SOURCE                      := {{source.dir}}

# +----------------------------------------------------------------------------+
# | MAKEFILE INCLUDES
# +----------------------------------------------------------------------------+
MAKEINCLUDE_MAKETARGETS         := $(DIR_BUILD)/{{templates.make_targets}}

# +----------------------------------------------------------------------------+
# | TARGETS
# +----------------------------------------------------------------------------+

.PHONY : all
all:
	# Nothing yet

.PHONY : init
init:
	@echo "init is not a valid make target. Did you mean '{{env.app_name}} init'?"

.PHONY : superclean
superclean:
	rm -rf $(DIR_BUILD)

# optional local overrides
-include local.mk

# use '{{env.app_name}} make-gen' to generate this makefile.
-include $(MAKEINCLUDE_MAKETARGETS)

