#  _____     _               
# |  _  |___| |_ _ _ ___ ___ 
# |     |  _|  _| | |  _| . |
# |__|__|_| |_| |___|_| |___|
# http://32bits.io/Arturo/
#

# +----------------------------------------------------------------------------+
# | BUILD CONFIGURATION
# +----------------------------------------------------------------------------+
VERSION_STRING                  := {{env.version}}
PROJECT_NAME                    := {{source.name}}
TARGET_PACKAGE                  := {{preferences.target_package}}
TARGET_PLATFORM                 := {{preferences.target_platform}}
BOARD                           := {{preferences.board}}

# +----------------------------------------------------------------------------+
# | DIRECTORIES AND CONFIGURATIONS
# +----------------------------------------------------------------------------+
DIR_BUILD                       := {{project.builddir}}
DIR_SOURCE                      := {{source.dir}}

# +----------------------------------------------------------------------------+
# | MAKEFILE INCLUDES
# +----------------------------------------------------------------------------+
MAKEINCLUDE_MAKETARGETS         := $(DIR_BUILD)/$(BOARD)/{{templates.make_targets}}
MAKEINCLUDE_MAKEHEX             := $(DIR_BUILD)/$(BOARD)/{{templates.make_hex}}

# +----------------------------------------------------------------------------+
# | TARGETS
# +----------------------------------------------------------------------------+

.PHONY : all
all:
	# Nothing yet

.PHONY : clean
clean:
	rm -rf $(BUILDDIR)

-include $(MAKEINCLUDE_MAKETARGETS)

